List pastTripItems = [
  {
    'location': 'Vidhan Soudha',
    'image': 'assets/image/trip.png',
    'date': '10 Oct 11:00 am',
    'fare': '100.00',
    'status': 1,
  },
  {
    'location': 'Electronic City',
    'image': 'assets/image/trip.png',
    'date': '05 Oct 09:45 pm',
    'fare': '300.00',
    'status': 1,
  },
  {
    'location': 'Vidhan Soudha',
    'image': 'assets/image/trip.png',
    'date': '10 Sep 11:00 am',
    'fare': '0.00',
    'status': 0,
  },
  {
    'location': 'Electronic City',
    'image': 'assets/image/trip.png',
    'date': '10 Sep 11:00 am',
    'fare': '0.00',
    'status': 0,
  },
  {
    'location': 'Vidhan Soudha',
    'image': 'assets/image/trip.png',
    'date': '10 Sep 11:00 am',
    'fare': '0.00',
    'status': 0,
  },
  {
    'location': 'Electronic City',
    'image': 'assets/image/trip.png',
    'date': '10 Sep 11:00 am',
    'fare': '0.00',
    'status': 0,
  },
  {
    'location': 'Vidhan Soudha',
    'image': 'assets/image/trip.png',
    'date': '10 Sep 11:00 am',
    'fare': '0.00',
    'status': 0,
  },
  {
    'location': 'Electronic City',
    'image': 'assets/image/trip.png',
    'date': '10 Sep 11:00 am',
    'fare': '0.00',
    'status': 0,
  },
];
